name: Deploy to AWS ECS

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get ECR repository URI
        id: ecr
        run: |
          URI=$(aws ecr describe-repositories \
            --repository-names "${{ secrets.ECR_REPOSITORY }}" \
            --query "repositories[0].repositoryUri" \
            --output text)
          echo "REPO_URI=$URI" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $REPO_URI:$IMAGE_TAG .

          docker push $REPO_URI:$IMAGE_TAG

      - name: Prepare new ECS task definition
        id: task-def
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition \
            --task-definition "${{ secrets.ECS_TASK_DEFINITION_FAMILY }}" \
            --query taskDefinition)

          NEW_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq \
            --arg IMAGE "$REPO_URI:$IMAGE_TAG" \
            '.containerDefinitions[0].image = $IMAGE | {
              family,
              taskRoleArn,
              executionRoleArn,
              networkMode,
              containerDefinitions,
              requiresCompatibilities,
              cpu,
              memory
            }'
          )

          echo "$NEW_TASK_DEF" > new-task-def.json

      - name: Register new task definition
        id: register-task
        run: |
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster "${{ secrets.ECS_CLUSTER }}" \
            --service "${{ secrets.ECS_SERVICE }}" \
            --task-definition "$TASK_DEF_ARN" \
            --force-new-deployment
